---
name: character_frequency_analysis
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.16.0
  very_good_analysis: ^5.0.0
